### ISSUE TITLE
Parser won't accept non-string default values

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-artifact-library#5]
Default values can be terms as well as strings (as far as I know).  However, the parser only accepts default values that are strings.

**Comment by martinjoconnor** [comment]
I checked and it seems that all default values need to be enclosed in quotes - even when they are numeric.

**Comment by matthewhorridge** [comment]
@martinjoconnor and for ontology terms?

**Comment by martinjoconnor** [comment]
Yes. It's really a UI-handled field and not really under the control of JSON Schema or JSON-LD - and I think the front end only generates and handles quote-enclosed values.

**Comment by matthewhorridge** [comment]
We are using default ontology terms for RADx.  Check [this](https://cedar.metadatacenter.org/fields/edit/https://repo.metadatacenter.org/template-fields/39623c1e-d41e-42d7-bd22-4464a8ce8214?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F5ac6dcb6-7a9b-4a75-a945-60ae43750953) out.  So the UI allows us to enter terms and they come out as JSON objects...

```json
"_valueConstraints": {
    "requiredValue": false,
    "multipleChoice": false,
    "classes": [],
    "branches": [
      {
        "source": "https://bioportal.bioontology.org/ontologies/FDC-GDMT",
        "acronym": "FDC-GDMT",
        "name": "FDC-GDMT",
        "uri": "http://vocab.fairdatacollective.org/gdmt/ResourceCreatorType",
        "maxDepth": 2147483647
      }
    ],
    "ontologies": [],
    "literals": [],
    "defaultValue": {
      "termUri": "http://vocab.fairdatacollective.org/gdmt/Person",
      "rdfs:label": "Person"
    }
}
```

<img width="775" alt="image" src="https://github.com/metadatacenter/cedar-artifact-library/assets/488607/87509b96-b00a-4e95-b930-85ca1292528b">

**Comment by martinjoconnor** [comment]
Was not aware of this. It's not documented anywhere, I think. I will need to look at updating - and perhaps handling values that are not quote-enclosed.

**Comment by martinjoconnor** [comment]
Now accepts numbers and ontology values with a URI and label
