### ISSUE TITLE
Provide a common method for getting child artifacts

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-artifact-library#6]
Often I just want to get all chid artifacts of any given artifact.  I typically do this for building a tree of a template.  It would be convenient if there was a method (on Artifact) call `getChildArtifacts` (or something similar) that returns a `List<Artifact>`.

At the moment, I do something like this:

```java
private List<SchemaArtifact> getChildren(SchemaArtifact schemaArtifact) {
        var result = new ArrayList<SchemaArtifact>();
        if(schemaArtifact instanceof TemplateSchemaArtifact tsa) {
            result.addAll(tsa.getElementSchemas().values());
            result.addAll(tsa.getFieldSchemas().values());
        }
        else if(schemaArtifact instanceof ElementSchemaArtifact esa) {
            result.addAll(esa.getElementSchemas().values());
            result.addAll(esa.getFieldSchemas().values());
        }
        return result;
}
```

**Comment by martinjoconnor** [comment]
I will add this method.

**Comment by martinjoconnor** [comment]
Method added. Called `getChildSchemas` in new interface called `ParentSchemaArtifact`. Returns in order specified by UI specification.
