### ISSUE TITLE
CamelCase Acronyms/Abbreviations (Minor Style Issue)

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-artifact-library#7]
Consider this before the library gets wider use.  Obviously there's some element of personal taste here,

Some of the method names contain acronyms or abbreviations, for example, `getJsonLDID`, that are akward to read but moreover, modern style guides (e.g. the [Google one](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)) in essence say acronyms should be [CamelCased](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case).  So, consider CamelCasing these, for example, `getJsonLdId`.  

FWIW, a few years ago I would name things `OWLClass` or `IRI` but now I'd use `OwlClass` and `Iri` after falling into line with wider community guidelines.

**Comment by martinjoconnor** [comment]
Makes sense. I will take a look at updating next week.

**Comment by martinjoconnor** [comment]
Updated method names to reflect this comment.
