### ISSUE TITLE
Add common methods (via a common interface) to get ordered children artifacts

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-artifact-library#8]
This is related to #6 but I would like the children to be ordered consistently, as defined in the UI element.

**Comment by martinjoconnor** [comment]
As per #6, `getChildSchemas` returns in order specified by UI element. Have modified following two methods to also return in correct UI-specified order:

```
LinkedHashMap<String, FieldSchemaArtifact> getFieldSchemas();
LinkedHashMap<String, ElementSchemaArtifact> getElementSchemas();
```
